name: tests

on: [push]

jobs:
  linux_tests:
    runs-on: ubuntu-20.04
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v2"

      - name: Composer
        uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          phpunit_version: 8.5

